### ISSUE TITLE
Show current path in status bar

### ISSUE THREAD

**Issue by shemerey** [ricardoemerson/yaml-path-copy#1]
Nice package, I Want to ask have you ever consider to show current path on status bar, It looks natural to show it there. The only problem I see is potential performance issue but can be wrong.

**Comment by ricardoemerson** [comment]
Hello Anton (shemerey). I appreciate your suggestion but I think that status bar not will comport all the path to some hierarchies and it will lost the functionality not displaying all the path. Because of this i decide to display it using notifications and if you need it possible to copy to clipboard too.

Although this, you can use another package called yaml-path. This package display on status bar the current path.

Thanks for the contact.

Regards,

Ricardo

**Comment by shemerey** [comment]
@ricardoemerson thx for you response, I am really appreciate your work.
